//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralExchRateService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuoteDesc", Namespace="http://schemas.datacontract.org/2004/07/ExchRatesWCFService.Models")]
    public partial class QuoteDesc : object
    {
        
        private string DateField;
        
        private string NameField;
        
        private CentralExchRateService.CurrencyQuoteDesc[] ValutesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CentralExchRateService.CurrencyQuoteDesc[] Valutes
        {
            get
            {
                return this.ValutesField;
            }
            set
            {
                this.ValutesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyQuoteDesc", Namespace="http://schemas.datacontract.org/2004/07/ExchRatesWCFService.Models")]
    public partial class CurrencyQuoteDesc : object
    {
        
        private string CharCodeField;
        
        private string IdField;
        
        private string NameField;
        
        private uint NominalField;
        
        private ushort NumCodeField;
        
        private string NumCodeStrField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CharCode
        {
            get
            {
                return this.CharCodeField;
            }
            set
            {
                this.CharCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Nominal
        {
            get
            {
                return this.NominalField;
            }
            set
            {
                this.NominalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort NumCode
        {
            get
            {
                return this.NumCodeField;
            }
            set
            {
                this.NumCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCodeStr
        {
            get
            {
                return this.NumCodeStrField;
            }
            set
            {
                this.NumCodeStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodesDesc", Namespace="http://schemas.datacontract.org/2004/07/ExchRatesWCFService.Models")]
    public partial class CodesDesc : object
    {
        
        private CentralExchRateService.CurrencyCodesDesc[] ItemsField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CentralExchRateService.CurrencyCodesDesc[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyCodesDesc", Namespace="http://schemas.datacontract.org/2004/07/ExchRatesWCFService.Models")]
    public partial class CurrencyCodesDesc : object
    {
        
        private string CharCodeField;
        
        private string EngNameField;
        
        private string IdField;
        
        private string NameField;
        
        private uint NominalField;
        
        private ushort NumCodeField;
        
        private string NumCodeStrField;
        
        private string ParentCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CharCode
        {
            get
            {
                return this.CharCodeField;
            }
            set
            {
                this.CharCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngName
        {
            get
            {
                return this.EngNameField;
            }
            set
            {
                this.EngNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Nominal
        {
            get
            {
                return this.NominalField;
            }
            set
            {
                this.NominalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort NumCode
        {
            get
            {
                return this.NumCodeField;
            }
            set
            {
                this.NumCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCodeStr
        {
            get
            {
                return this.NumCodeStrField;
            }
            set
            {
                this.NumCodeStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentCode
        {
            get
            {
                return this.ParentCodeField;
            }
            set
            {
                this.ParentCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentralExchRateService.ICentralExchRateService")]
    public interface ICentralExchRateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralExchRateService/GetCurrencyQuotesDesc", ReplyAction="http://tempuri.org/ICentralExchRateService/GetCurrencyQuotesDescResponse")]
        System.Threading.Tasks.Task<CentralExchRateService.QuoteDesc> GetCurrencyQuotesDescAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralExchRateService/GetCurrencyCodesDesc", ReplyAction="http://tempuri.org/ICentralExchRateService/GetCurrencyCodesDescResponse")]
        System.Threading.Tasks.Task<CentralExchRateService.CodesDesc> GetCurrencyCodesDescAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICentralExchRateServiceChannel : CentralExchRateService.ICentralExchRateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CentralExchRateServiceClient : System.ServiceModel.ClientBase<CentralExchRateService.ICentralExchRateService>, CentralExchRateService.ICentralExchRateService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CentralExchRateServiceClient() : 
                base(CentralExchRateServiceClient.GetDefaultBinding(), CentralExchRateServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICentralExchRateService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralExchRateServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CentralExchRateServiceClient.GetBindingForEndpoint(endpointConfiguration), CentralExchRateServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralExchRateServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CentralExchRateServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralExchRateServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CentralExchRateServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CentralExchRateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CentralExchRateService.QuoteDesc> GetCurrencyQuotesDescAsync(System.DateTime date)
        {
            return base.Channel.GetCurrencyQuotesDescAsync(date);
        }
        
        public System.Threading.Tasks.Task<CentralExchRateService.CodesDesc> GetCurrencyCodesDescAsync()
        {
            return base.Channel.GetCurrencyCodesDescAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICentralExchRateService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICentralExchRateService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51041/CentralExchRateService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CentralExchRateServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICentralExchRateService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CentralExchRateServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICentralExchRateService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICentralExchRateService,
        }
    }
}
